name: Build and publish the Docker image

permissions:
  id-token: write
  contents: read
  actions: write

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Build and publish (linux/arm64)
    runs-on: ubuntu-24.04-arm
    env:
      ENVIRONMENT: prod
      APP_NAME: sonata-cell-position
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.AWS_ECR_PUBLISH_ROLE_ARN }}
          aws-region: ${{ vars.PUBLICECR_REGION }}

      - name: Authenticate with AWS Public ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push
        id: build
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: linux/arm64
          tags: ${{ vars.PUBLICECR_URI }}:${{ github.ref_name }}
          build-args: |
            ENVIRONMENT=prod
            APP_NAME=sonata-cell-position
            APP_VERSION=${{ github.ref_name }}
            COMMIT_SHA=${{ github.sha }}
          cache-from: type=gha,scope=linux/arm64
          cache-to: type=gha,mode=max,scope=linux/arm64
          provenance: false
          sbom: false
          push: true

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ vars.PUBLICECR_URI }}:${{ github.ref_name }}
